<?php

namespace Kivii\Services;

/**
 * Default services catalog for initial plugin setup.
 */
class DefaultServiceCatalog {

    public static function get(): array {
        return [
            [
                'category' => [
                    'name_nl'        => 'Onderhoud',
                    'name_en'        => 'Maintenance',
                    'description_nl' => 'Jaarlijkse onderhoudsbeurt volgens fabrieksspecificaties.',
                    'description_en' => 'Annual maintenance according to manufacturer specifications.',
                    'sort_order'     => 10,
                    'is_active'      => 1,
                ],
                'services' => [
                    [
                        'title_nl'         => 'Kleine beurt',
                        'title_en'         => 'Basic service',
                        'description_nl'   => 'Basisonderhoud voor olie, filters en controlepunten.',
                        'description_en'   => 'Basic maintenance for oil, filters, and inspection points.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 149.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 90,
                        'is_addon'         => 0,
                        'is_active'        => 1,
                        'sort_order'       => 10,
                    ],
                    [
                        'title_nl'         => 'Grote beurt',
                        'title_en'         => 'Major service',
                        'description_nl'   => 'Uitgebreide onderhoudsbeurt met extra controlepunten.',
                        'description_en'   => 'Extended maintenance service with additional inspection points.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 289.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 150,
                        'is_addon'         => 0,
                        'is_active'        => 1,
                        'sort_order'       => 20,
                    ],
                    [
                        'title_nl'         => 'Elektrische voertuigen onderhoudsservice',
                        'title_en'         => 'Electric vehicle maintenance service',
                        'description_nl'   => 'Aanbevolen onderhoudsservice volgens fabrieksopgave.',
                        'description_en'   => 'Recommended maintenance service according to manufacturer guidelines.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 169.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 90,
                        'is_addon'         => 0,
                        'is_active'        => 1,
                        'sort_order'       => 30,
                    ],
                    [
                        'title_nl'         => 'Geen onderhoud nodig',
                        'title_en'         => 'No maintenance needed',
                        'description_nl'   => 'Selecteer alleen aanvullende werkzaamheden indien gewenst.',
                        'description_en'   => 'Only select additional services if needed.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 0,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 5,
                        'is_addon'         => 0,
                        'is_active'        => 1,
                        'sort_order'       => 40,
                    ],
                ],
            ],
            [
                'category' => [
                    'name_nl'        => 'Aanvullende werkzaamheden',
                    'name_en'        => 'Additional services',
                    'description_nl' => 'Kies werkzaamheden die aan uw auto moeten gebeuren.',
                    'description_en' => 'Choose any additional services needed for your car.',
                    'sort_order'     => 20,
                    'is_active'      => 1,
                ],
                'services' => [
                    [
                        'title_nl'         => 'APK keuring (Benzine, LPG en Elektrisch)',
                        'title_en'         => 'MOT inspection (Petrol, LPG and Electric)',
                        'description_nl'   => 'Benzine, LPG en Elek APK keuring.',
                        'description_en'   => 'MOT inspection for petrol, LPG and electric vehicles.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 54.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 45,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 10,
                    ],
                    [
                        'title_nl'         => 'Diesel voertuigen APK keuring',
                        'title_en'         => 'MOT inspection for diesel vehicles',
                        'description_nl'   => 'Inclusief deeltjesteller test, verplicht vanaf 01-2023.',
                        'description_en'   => 'Includes particulate counter test, mandatory since 01-2023.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 72.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 60,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 20,
                    ],
                    [
                        'title_nl'         => 'Oldtimer APK',
                        'title_en'         => 'Classic car MOT inspection',
                        'description_nl'   => 'APK-keuring voor oldtimers.',
                        'description_en'   => 'MOT inspection for classic cars.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 74.00,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 60,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 30,
                    ],
                    [
                        'title_nl'         => 'Distributieriem vervangen',
                        'title_en'         => 'Replace timing belt',
                        'description_nl'   => 'Prijs en duur op aanvraag afhankelijk van motortype.',
                        'description_en'   => 'Price and duration on request depending on engine type.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 0,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 240,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 40,
                    ],
                    [
                        'title_nl'         => 'Remmen rondom schoonmaken en gangbaar maken',
                        'title_en'         => 'Clean and free up brakes all around',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 124.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 90,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 50,
                    ],
                    [
                        'title_nl'         => 'Winter of zomer bandenset monteren',
                        'title_en'         => 'Mount winter or summer wheel set',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 44.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 45,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 60,
                    ],
                    [
                        'title_nl'         => 'Winter of zomerbanden monteren (zonder velg)',
                        'title_en'         => 'Mount winter or summer tires (without rims)',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 89.00,
                        'price_label_nl'   => 'Vanaf € 89,00',
                        'price_label_en'   => 'From € 89.00',
                        'duration_minutes' => 60,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 70,
                    ],
                    [
                        'title_nl'         => 'Tesla! Banden rouleren',
                        'title_en'         => 'Tesla tire rotation',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 44.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 30,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 80,
                    ],
                    [
                        'title_nl'         => 'Periodiek remvloeistof verversen',
                        'title_en'         => 'Periodic brake fluid replacement',
                        'description_nl'   => 'Elke 2 jaar aanbevolen.',
                        'description_en'   => 'Recommended every 2 years.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 45.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 45,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 90,
                    ],
                    [
                        'title_nl'         => 'Airco onderhoudsbeurt',
                        'title_en'         => 'Air conditioning service',
                        'description_nl'   => 'Elke 2 jaar, meerprijs bij meer dan 200 gram koudemiddel.',
                        'description_en'   => 'Every 2 years, surcharge applies above 200 grams of refrigerant.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 89.00,
                        'price_label_nl'   => 'Vanaf € 89,00',
                        'price_label_en'   => 'From € 89.00',
                        'duration_minutes' => 60,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 100,
                    ],
                    [
                        'title_nl'         => 'Elektrische en hybride airco onderhoudsbeurt',
                        'title_en'         => 'Electric and hybrid AC service',
                        'description_nl'   => 'Elke 2 jaar, meerprijs bij meer dan 200 gram koudemiddel.',
                        'description_en'   => 'Every 2 years, surcharge applies above 200 grams of refrigerant.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 135.00,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 75,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 110,
                    ],
                    [
                        'title_nl'         => 'Airco reinigen',
                        'title_en'         => 'Air conditioning cleaning',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 34.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 30,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 120,
                    ],
                    [
                        'title_nl'         => 'Tesla PTC heater vervangen (Model 3/Y)',
                        'title_en'         => 'Replace Tesla PTC heater (Model 3/Y)',
                        'description_nl'   => 'PTC heater Tesla Model 3/Y vervangen.',
                        'description_en'   => 'Replace PTC heater for Tesla Model 3/Y.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 1150.00,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 300,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 130,
                    ],
                    [
                        'title_nl'         => 'Tesla PTC heater vervangen (Model S/X)',
                        'title_en'         => 'Replace Tesla PTC heater (Model S/X)',
                        'description_nl'   => 'PTC heater Tesla Model S/X vervangen.',
                        'description_en'   => 'Replace PTC heater for Tesla Model S/X.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 1640.00,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 420,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 140,
                    ],
                    [
                        'title_nl'         => 'Tesla PTC heater S/X zekering Junction Box vervangen',
                        'title_en'         => 'Replace Tesla S/X PTC heater Junction Box fuse',
                        'description_nl'   => 'Zekering Junction Box (DC/DC-converter) vervangen en S/X PTC heater vervangen.',
                        'description_en'   => 'Replace Junction Box fuse (DC/DC converter) and S/X PTC heater.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 668.00,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 240,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 150,
                    ],
                    [
                        'title_nl'         => 'Tesla accudiagnose / accu onbalans',
                        'title_en'         => 'Tesla battery diagnosis / imbalance',
                        'description_nl'   => 'Diagnose van Tesla tractiebatterij en eventuele onbalans.',
                        'description_en'   => 'Diagnosis of Tesla traction battery and possible cell imbalance.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 0,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 90,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 160,
                    ],
                    [
                        'title_nl'         => 'Tesla! Vervangen droogmiddelzak Tesla 3/Y i.c.m. aircoservice beurt',
                        'title_en'         => 'Replace Tesla 3/Y desiccant bag with AC service',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 314.00,
                        'price_label_nl'   => 'Vanaf € 314,00',
                        'price_label_en'   => 'From € 314.00',
                        'duration_minutes' => 180,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 170,
                    ],
                    [
                        'title_nl'         => 'Tesla vervangen droogmiddelzak Tesla S/X i.c.m. aircoservice beurt',
                        'title_en'         => 'Replace Tesla S/X desiccant bag with AC service',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 204.00,
                        'price_label_nl'   => 'Vanaf € 204,00',
                        'price_label_en'   => 'From € 204.00',
                        'duration_minutes' => 150,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 180,
                    ],
                    [
                        'title_nl'         => 'Tip! Flacon motorolie bijleveren (1 liter)',
                        'title_en'         => 'Tip! Add 1 liter engine oil bottle',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 16.50,
                        'price_label_nl'   => 'Vanaf € 16,50',
                        'price_label_en'   => 'From € 16.50',
                        'duration_minutes' => 5,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 190,
                    ],
                    [
                        'title_nl'         => 'Ruitenwisserbladen voorzijde vervangen',
                        'title_en'         => 'Replace front wiper blades',
                        'description_nl'   => 'Prijs afhankelijk van voertuigtype en merk.',
                        'description_en'   => 'Price depends on vehicle type and brand.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 0,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 15,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 200,
                    ],
                    [
                        'title_nl'         => 'Ruitenwisserblad achterzijde vervangen',
                        'title_en'         => 'Replace rear wiper blade',
                        'description_nl'   => 'Prijs afhankelijk van voertuigtype en merk.',
                        'description_en'   => 'Price depends on vehicle type and brand.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 0,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 10,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 210,
                    ],
                    [
                        'title_nl'         => 'Wintercheck',
                        'title_en'         => 'Winter check',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 19.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 20,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 220,
                    ],
                    [
                        'title_nl'         => 'Zomercheck',
                        'title_en'         => 'Summer check',
                        'description_nl'   => '',
                        'description_en'   => '',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 19.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 20,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 230,
                    ],
                    [
                        'title_nl'         => 'Tip! Inlaatsysteem laten reinigen',
                        'title_en'         => 'Tip! Intake system cleaning',
                        'description_nl'   => 'Kan een brandstofbesparing tussen 10% en 30% opleveren.',
                        'description_en'   => 'May improve fuel economy by 10% to 30%.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 389.00,
                        'price_label_nl'   => 'Vanaf € 389,00',
                        'price_label_en'   => 'From € 389.00',
                        'duration_minutes' => 180,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 240,
                    ],
                    [
                        'title_nl'         => 'Tip! Hoog olieverbruik? Intensieve oliesysteem reiniging en bescherming',
                        'title_en'         => 'Tip! Intensive oil system cleaning and protection',
                        'description_nl'   => 'Alleen i.c.m. onderhoudsbeurt.',
                        'description_en'   => 'Only in combination with a maintenance service.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 114.95,
                        'price_label_nl'   => 'Vanaf € 114,95',
                        'price_label_en'   => 'From € 114.95',
                        'duration_minutes' => 90,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 250,
                    ],
                    [
                        'title_nl'         => 'Tip! Oliesysteem reiniging (FLUSH) en toevoeging aan de motorolie',
                        'title_en'         => 'Tip! Oil system flush and protective oil additive',
                        'description_nl'   => 'Voor extra bescherming, alleen i.c.m. onderhoudsbeurt.',
                        'description_en'   => 'For extra protection, only in combination with a maintenance service.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 49.95,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 30,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 260,
                    ],
                    [
                        'title_nl'         => 'Controle "einde contract"',
                        'title_en'         => 'End-of-contract inspection',
                        'description_nl'   => 'Controle voor inleveren of einde leasecontract.',
                        'description_en'   => 'Inspection before vehicle return or lease end.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 0,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 45,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 270,
                    ],
                    [
                        'title_nl'         => 'Andere werkzaamheden welke niet vermeld staan',
                        'title_en'         => 'Other services not listed',
                        'description_nl'   => 'Beschrijf andere werkzaamheden in de opmerkingen.',
                        'description_en'   => 'Describe any other requested work in the remarks field.',
                        'long_desc_nl'     => '',
                        'long_desc_en'     => '',
                        'price'            => 0,
                        'price_label_nl'   => '',
                        'price_label_en'   => '',
                        'duration_minutes' => 30,
                        'is_addon'         => 1,
                        'is_active'        => 1,
                        'sort_order'       => 280,
                    ],
                ],
            ],
        ];
    }
}
